name: Setup Workflow

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      frontend-directory: frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: frontend
        run: npm install
