name: Run Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest # Ubuntu som körmiljö

    steps:
      # Steg 1: Klona projektet från GitHub
      - name: Checkout repository
        uses: actions/checkout@v3

      # Steg 2: Installera Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Steg 3: Installera projektets beroenden
      - name: Install dependencies
        working-directory: frontend
        run: npm install

      # Steg 4: Starta Vite-utvecklingsservern
      - name: Start Vite dev server
        working-directory: frontend
        run: npm run dev

      # Steg 5: Kör End-to-End (E2E) tester med Cypress
      - name: Run Cypress E2E tests
        working-directory: frontend
        run: npx cypress run --spec 'cypress/e2e/**/*' # Kör E2E-tester

      # Steg 6: Kör komponenttester med Cypress
      - name: Run Cypress Component Tests
        working-directory: frontend
        run: npx cypress run --component # Kör komponenttester
