name: Cypress Tests

on:
  push:
    branches: [main]

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: frontend
        run: npm install
      - name: Lint code
        working-directory: frontend
        run: npm run lint
      - name: Type check
        working-directory: frontend
        run: npm run type-check
      - name: Run tests
        working-directory: frontend
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: frontend
        run: npm install
      - name: Build project
        working-directory: frontend
        run: npm run build

  e2e-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: frontend
        run: npm install
      - name: Start server
        working-directory: frontend
        run: npm run preview &
      - name: Run Cypress tests
        working-directory: frontend
        run: npx cypress run

  component-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: frontend
        run: npm install
      - name: Start server
        working-directory: frontend
        run: npm run preview &
      - name: Run Cypress component tests
        working-directory: frontend
        run: npx cypress run --component
