name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Proje kodunu al
      - name: Checkout repository
        uses: actions/checkout@v3

      # Node.js kurulumu
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Bağımlılıkları yükle
      - name: Install dependencies
        working-directory: frontend
        run: npm install

      # Vite geliştirme sunucusunu başlat
      - name: Start Vite dev server
        working-directory: frontend
        run: |
          npm run dev &
          sleep 10

      # Cypress testlerini çalıştır
      - name: Run Cypress tests
        working-directory: frontend
        run: npx cypress run
