name: Run Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  # Setup iş akışını başlatıyoruz
  setup:
    uses: ./.github/workflows/setup.yml
    with:
      frontend-directory: frontend

  # Lint- och typkontrolljobb
  lint-typecheck:
    runs-on: ubuntu-latest
    needs: setup # setup job'ını bekle
    uses: ./.github/workflows/setup.yml
    with:
      frontend-directory: frontend
    steps:
      - name: Lint code
        working-directory: frontend
        run: npm run lint

      - name: Type check
        working-directory: frontend
        run: npm run type-check

  # Testjobb
  tests:
    runs-on: ubuntu-latest
    needs: setup # setup job'ını bekle
    uses: ./.github/workflows/setup.yml
    with:
      frontend-directory: frontend
    steps:
      - name: Start Vite dev server
        working-directory: frontend
        run: |
          npm run dev & # Start server in background
          sleep 10      # Wait for server to start

      - name: Run Cypress E2E tests
        working-directory: frontend
        run: npm run test --spec 'cypress/e2e/**/*'

      - name: Run Cypress Component Tests
        working-directory: frontend
        run: npm run test --component
